### ISSUE TITLE
merge conflicts with merge from k8s upstream job

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/kubernetes-jenkins#237]
Currently, we are unable to keep our master k8s branch in sync with upstream. This is due to the fact that a few PR's have been merged into our repo's master which then diverges from upstream master and conflicts arise.

I think the best way to handle this is to always keep upstream and our repo's master in sync. PR's should then be opened against a different branch, something like 'develop'. Then we can merge PR's into that branch at will and when ready, we can propose a PR upstream to get that merged into master, subsequently, making it back down into our forked master branch.

I'm still trying to understand how the flow should work, and this is what I've come up with so far. Suggestions/corrections welcomed.

/cc @tvansteenburgh @ktsakalozos @kwmonroe @Cynerva @hyperbolic2346 @johnsca

**Comment by tvansteenburgh** [comment]
+1 to the proposed workflow. I'm surprised by the divergence though, since I wouldn't expect many (if any) upstream commits to touch anything under cluster/juju.

**Comment by johnsca** [comment]
Could the conflicts just be from the transition period?  Though, having outside PRs for the charms causing conflicts is a good problem to have.  Either way, +1 to the proposal.

**Comment by hyperbolic2346** [comment]
While I'm fine with using a dev branch, I would point out that the plan for this issue was to manually merge when this happened. I just did that. We had a PR submit upstream that altered config and a PR submit to our repo that did the same. This will cease to be an issue when we no longer submit to either project. It will continue to show up for anything that is merged into the charm code though. The thought was that this would be so rare that manually merging wouldn't be an issue.

**Comment by Cynerva** [comment]
> I'm surprised by the divergence though, since I wouldn't expect many (if any) upstream commits to touch anything under cluster/juju.

This happens surprisingly often. Here's one from a month ago that I just happened to see yesterday: https://github.com/kubernetes/kubernetes/pull/66039

**Comment by battlemidget** [comment]
To recap, the git commit history has been cleaned up, we pull from upstream master, and perform a rebase on whatever's latest being pulled in.
